-- Reference upsert body for CDSL export.
-- The executable application query, including the full source CTE, lives in:
--   server/queries/cdslExportQueries.js
-- This file keeps the INSERT ... ON CONFLICT shape visible for pgAdmin review.

INSERT INTO public.cdsl_data (
  application_id,
  upload_id,
  dpid,
  operator_id,
  bo_id,
  bo_request_receive_date,
  product_number,
  bo_name,
  bo_middle_name,
  last_name,
  bo_title,
  bo_suffix,
  father_husband_name,
  cust_addr_1,
  cust_addr_2,
  cust_addr_3,
  cust_addr_cntry_code,
  cust_addr_zip,
  cust_addr_state_code,
  cust_addr_state,
  cust_addr_city,
  city_sequence_number,
  primary_mobile_no_isd_code,
  primary_mobile_no,
  income_tax_pan,
  uid,
  uid_verification_flag,
  poa_type_flag,
  primary_email,
  pan_verification_flag,
  signature_file_flag,
  date_of_birth_or_origin,
  sex_code,
  annual_income_code,
  nationality_code,
  bo_fee_type,
  nomination_opt_out,
  bonafide_flag,
  email_statement_flag,
  annual_report_flag,
  bsda_flag,
  mode_of_operation,
  communication_preference,
  bo_category,
  bo_settlement_planning_flag,
  dividend_bank_ifsc_code,
  beneficiary_tax_deduction_status,
  bo_sub_status,
  bo_statement_cycle_code,
  dividend_bank_acct_type,
  dividend_bank_code,
  dividend_acct_numb,
  dividend_bank_ccy,
  request_payload,
  updated_at
)
SELECT
  application_id,
  upload_id,
  dpid,
  operator_id,
  bo_id,
  bo_request_receive_date,
  product_number,
  bo_name,
  bo_middle_name,
  last_name,
  bo_title,
  bo_suffix,
  father_husband_name,
  cust_addr_1,
  cust_addr_2,
  cust_addr_3,
  cust_addr_cntry_code,
  cust_addr_zip,
  cust_addr_state_code,
  cust_addr_state,
  cust_addr_city,
  city_sequence_number,
  primary_mobile_no_isd_code,
  primary_mobile_no,
  income_tax_pan,
  uid,
  uid_verification_flag,
  poa_type_flag,
  primary_email,
  pan_verification_flag,
  signature_file_flag,
  date_of_birth_or_origin,
  sex_code,
  annual_income_code,
  nationality_code,
  bo_fee_type,
  nomination_opt_out,
  bonafide_flag,
  email_statement_flag,
  annual_report_flag,
  bsda_flag,
  mode_of_operation,
  communication_preference,
  bo_category,
  bo_settlement_planning_flag,
  dividend_bank_ifsc_code,
  beneficiary_tax_deduction_status,
  bo_sub_status,
  bo_statement_cycle_code,
  dividend_bank_acct_type,
  dividend_bank_code,
  dividend_acct_numb,
  dividend_bank_ccy,
  request_payload,
  NOW()
FROM prepared_row
WHERE application_id = $1
ON CONFLICT (application_id) DO UPDATE SET
  upload_id = EXCLUDED.upload_id,
  dpid = EXCLUDED.dpid,
  operator_id = EXCLUDED.operator_id,
  bo_id = EXCLUDED.bo_id,
  bo_request_receive_date = EXCLUDED.bo_request_receive_date,
  product_number = EXCLUDED.product_number,
  bo_name = EXCLUDED.bo_name,
  bo_middle_name = EXCLUDED.bo_middle_name,
  last_name = EXCLUDED.last_name,
  bo_title = EXCLUDED.bo_title,
  bo_suffix = EXCLUDED.bo_suffix,
  father_husband_name = EXCLUDED.father_husband_name,
  cust_addr_1 = EXCLUDED.cust_addr_1,
  cust_addr_2 = EXCLUDED.cust_addr_2,
  cust_addr_3 = EXCLUDED.cust_addr_3,
  cust_addr_cntry_code = EXCLUDED.cust_addr_cntry_code,
  cust_addr_zip = EXCLUDED.cust_addr_zip,
  cust_addr_state_code = EXCLUDED.cust_addr_state_code,
  cust_addr_state = EXCLUDED.cust_addr_state,
  cust_addr_city = EXCLUDED.cust_addr_city,
  city_sequence_number = EXCLUDED.city_sequence_number,
  primary_mobile_no_isd_code = EXCLUDED.primary_mobile_no_isd_code,
  primary_mobile_no = EXCLUDED.primary_mobile_no,
  income_tax_pan = EXCLUDED.income_tax_pan,
  uid = EXCLUDED.uid,
  uid_verification_flag = EXCLUDED.uid_verification_flag,
  poa_type_flag = EXCLUDED.poa_type_flag,
  primary_email = EXCLUDED.primary_email,
  pan_verification_flag = EXCLUDED.pan_verification_flag,
  signature_file_flag = EXCLUDED.signature_file_flag,
  date_of_birth_or_origin = EXCLUDED.date_of_birth_or_origin,
  sex_code = EXCLUDED.sex_code,
  annual_income_code = EXCLUDED.annual_income_code,
  nationality_code = EXCLUDED.nationality_code,
  bo_fee_type = EXCLUDED.bo_fee_type,
  nomination_opt_out = EXCLUDED.nomination_opt_out,
  bonafide_flag = EXCLUDED.bonafide_flag,
  email_statement_flag = EXCLUDED.email_statement_flag,
  annual_report_flag = EXCLUDED.annual_report_flag,
  bsda_flag = EXCLUDED.bsda_flag,
  mode_of_operation = EXCLUDED.mode_of_operation,
  communication_preference = EXCLUDED.communication_preference,
  bo_category = EXCLUDED.bo_category,
  bo_settlement_planning_flag = EXCLUDED.bo_settlement_planning_flag,
  dividend_bank_ifsc_code = EXCLUDED.dividend_bank_ifsc_code,
  beneficiary_tax_deduction_status = EXCLUDED.beneficiary_tax_deduction_status,
  bo_sub_status = EXCLUDED.bo_sub_status,
  bo_statement_cycle_code = EXCLUDED.bo_statement_cycle_code,
  dividend_bank_acct_type = EXCLUDED.dividend_bank_acct_type,
  dividend_bank_code = EXCLUDED.dividend_bank_code,
  dividend_acct_numb = EXCLUDED.dividend_acct_numb,
  dividend_bank_ccy = EXCLUDED.dividend_bank_ccy,
  request_payload = EXCLUDED.request_payload,
  updated_at = NOW();
