-- Reference upsert body for BSE export.
-- The executable application query, including the full source CTE, lives in:
--   server/queries/bseExportQueries.js
-- This file keeps the INSERT ... ON CONFLICT shape visible for pgAdmin review.

INSERT INTO public.bse_data (
  application_id,
  transaction_code,
  client_type,
  status,
  category,
  client_code,
  pan_no,
  political_ex_person,
  address1,
  permn_equal_corp,
  address2,
  country,
  state,
  city,
  pincode,
  type_of_service,
  contact_details,
  email,
  mobile_number,
  std_code,
  phone_no,
  depository_name1,
  demat_id1,
  depository_participant1,
  bank_name1,
  account_no1,
  provide_details,
  income,
  net_worth,
  is_active,
  first_name,
  middle_name,
  last_name,
  aadhaar_card_no,
  date_of_birth,
  client_name,
  whether_corporate,
  number_of_directors,
  is_poa,
  poa_for_fund,
  poa_for_security,
  per_country,
  per_state,
  per_city,
  per_pincode,
  opted_for_nomination,
  beneficial_own_acnt_no1,
  opted_for_upi,
  bank_branch_ifsc_code1,
  primary_or_secondary_bank1,
  primary_or_secondary_dp1,
  request_payload,
  updated_at
)
SELECT
  source_row.application_id,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM public.bse_data existing_bse
      WHERE existing_bse.application_id = source_row.application_id
    )
    THEN 'M'
    ELSE 'N'
  END AS transaction_code,
  'I' AS client_type,
  'CL' AS status,
  source_row.source_bse_category AS category,
  source_row.source_client_code AS client_code,
  source_row.source_pan_number AS pan_no,
  source_row.source_political_ex_person AS political_ex_person,
  source_row.source_address_line1 AS address1,
  NULL::varchar AS permn_equal_corp,
  source_row.source_address_line2 AS address2,
  source_row.source_country AS country,
  source_row.source_state AS state,
  source_row.source_city AS city,
  source_row.source_pincode AS pincode,
  NULL::varchar AS type_of_service,
  NULL::varchar AS contact_details,
  source_row.source_email AS email,
  source_row.source_mobile AS mobile_number,
  NULL::varchar AS std_code,
  NULL::varchar AS phone_no,
  source_row.source_depository_name1 AS depository_name1,
  NULL::varchar AS demat_id1,
  NULL::varchar AS depository_participant1,
  source_row.source_bank_name AS bank_name1,
  source_row.source_bank_account_number AS account_no1,
  NULL::varchar AS provide_details,
  NULL::varchar AS income,
  source_row.source_net_worth AS net_worth,
  'Y' AS is_active,
  source_row.source_first_name AS first_name,
  source_row.source_middle_name AS middle_name,
  source_row.source_last_name AS last_name,
  source_row.source_aadhaar_number AS aadhaar_card_no,
  source_row.source_date_of_birth AS date_of_birth,
  source_row.source_client_name AS client_name,
  'N' AS whether_corporate,
  0 AS number_of_directors,
  source_row.source_is_poa AS is_poa,
  NULL::varchar AS poa_for_fund,
  NULL::varchar AS poa_for_security,
  source_row.source_country AS per_country,
  source_row.source_state AS per_state,
  source_row.source_city AS per_city,
  source_row.source_pincode AS per_pincode,
  source_row.source_opted_for_nomination AS opted_for_nomination,
  source_row.source_boid AS beneficial_own_acnt_no1,
  NULL::varchar AS opted_for_upi,
  source_row.source_bank_ifsc AS bank_branch_ifsc_code1,
  'P' AS primary_or_secondary_bank1,
  'P' AS primary_or_secondary_dp1,
  source_row.request_payload,
  NOW() AS updated_at
FROM source_row
WHERE application_id = $1
ON CONFLICT (application_id) DO UPDATE SET
  transaction_code = EXCLUDED.transaction_code,
  client_type = EXCLUDED.client_type,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  client_code = EXCLUDED.client_code,
  pan_no = EXCLUDED.pan_no,
  political_ex_person = EXCLUDED.political_ex_person,
  address1 = EXCLUDED.address1,
  permn_equal_corp = EXCLUDED.permn_equal_corp,
  address2 = EXCLUDED.address2,
  country = EXCLUDED.country,
  state = EXCLUDED.state,
  city = EXCLUDED.city,
  pincode = EXCLUDED.pincode,
  type_of_service = EXCLUDED.type_of_service,
  contact_details = EXCLUDED.contact_details,
  email = EXCLUDED.email,
  mobile_number = EXCLUDED.mobile_number,
  std_code = EXCLUDED.std_code,
  phone_no = EXCLUDED.phone_no,
  depository_name1 = EXCLUDED.depository_name1,
  demat_id1 = EXCLUDED.demat_id1,
  depository_participant1 = EXCLUDED.depository_participant1,
  bank_name1 = EXCLUDED.bank_name1,
  account_no1 = EXCLUDED.account_no1,
  provide_details = EXCLUDED.provide_details,
  income = EXCLUDED.income,
  net_worth = EXCLUDED.net_worth,
  is_active = EXCLUDED.is_active,
  first_name = EXCLUDED.first_name,
  middle_name = EXCLUDED.middle_name,
  last_name = EXCLUDED.last_name,
  aadhaar_card_no = EXCLUDED.aadhaar_card_no,
  date_of_birth = EXCLUDED.date_of_birth,
  client_name = EXCLUDED.client_name,
  whether_corporate = EXCLUDED.whether_corporate,
  number_of_directors = EXCLUDED.number_of_directors,
  is_poa = EXCLUDED.is_poa,
  poa_for_fund = EXCLUDED.poa_for_fund,
  poa_for_security = EXCLUDED.poa_for_security,
  per_country = EXCLUDED.per_country,
  per_state = EXCLUDED.per_state,
  per_city = EXCLUDED.per_city,
  per_pincode = EXCLUDED.per_pincode,
  opted_for_nomination = EXCLUDED.opted_for_nomination,
  beneficial_own_acnt_no1 = EXCLUDED.beneficial_own_acnt_no1,
  opted_for_upi = EXCLUDED.opted_for_upi,
  bank_branch_ifsc_code1 = EXCLUDED.bank_branch_ifsc_code1,
  primary_or_secondary_bank1 = EXCLUDED.primary_or_secondary_bank1,
  primary_or_secondary_dp1 = EXCLUDED.primary_or_secondary_dp1,
  request_payload = EXCLUDED.request_payload,
  updated_at = NOW();
