CREATE TABLE IF NOT EXISTS public.nsdl_data (
  id BIGSERIAL PRIMARY KEY,
  application_id BIGINT NOT NULL,
  botxntyp VARCHAR(5),
  cntrlsctiesdpstryptcptrole VARCHAR(2),
  cntrlsctiesdpstryptcpt VARCHAR(8),
  brnchid VARCHAR(6),
  btchid INTEGER,
  chnlid VARCHAR(3),
  sgn TEXT,
  sgntrsz INTEGER,
  postvconf VARCHAR(3),
  nonmntnflg VARCHAR(3),
  prdnb VARCHAR(5),
  bnfcrysubtp VARCHAR(5),
  bnfcryshrtnm VARCHAR(16),
  bnfcryacctctgy VARCHAR(3),
  ocptn VARCHAR(4),
  adrprefflg VARCHAR(3),
  comtobesentto VARCHAR(3),
  corad_purpcd VARCHAR(5),
  corad_addmoddelind VARCHAR(3),
  corad_adr1 VARCHAR(55),
  corad_adr2 VARCHAR(55),
  corad_adr3 VARCHAR(55),
  corad_adr4orcity VARCHAR(55),
  corad_ctry VARCHAR(3),
  corad_pstcd VARCHAR(10),
  corad_ctrysubdvsncd VARCHAR(13),
  grssanlincmrg VARCHAR(6),
  netwrth NUMERIC(18, 2),
  netwrthasondt VARCHAR(10),
  bnfcrytaxddctnsts VARCHAR(5),
  bnfcrybkacctnb VARCHAR(30),
  bkaccttp VARCHAR(3),
  bnfcrybknm VARCHAR(35),
  inifsc VARCHAR(15),
  holder_purpse VARCHAR(4),
  holder_frstnm VARCHAR(135),
  holder_scndhldrnmoffthr VARCHAR(50),
  holder_birthdt VARCHAR(10),
  holder_gndr VARCHAR(5),
  holder_pan VARCHAR(10),
  holder_panvrfyflg VARCHAR(6),
  holder_uid VARCHAR(16),
  holder_smsfclty VARCHAR(3),
  holder_prmryisdcd VARCHAR(6),
  holder_mobnb VARCHAR(17),
  holder_fmlyflgformobnbof VARCHAR(3),
  holder_emailadr VARCHAR(100),
  holder_fmlyflgforemailadr VARCHAR(3),
  holder_addmoddelind VARCHAR(3),
  request_payload JSONB,
  response_payload JSONB,
  nsdl_push_status VARCHAR(30),
  nsdl_msg_code VARCHAR(30),
  nsdl_msg_desc TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
