CREATE TABLE IF NOT EXISTS public.mf_data (
  id BIGSERIAL PRIMARY KEY,
  application_id BIGINT NOT NULL,
  regn_type VARCHAR(10),
  client_code VARCHAR(10),
  primary_holder_first_name VARCHAR(70),
  primary_holder_middle_name VARCHAR(70),
  primary_holder_last_name VARCHAR(70),
  tax_status VARCHAR(2),
  gender VARCHAR(1),
  primary_holder_dob VARCHAR(10),
  occupation_code VARCHAR(2),
  holding_nature VARCHAR(2),
  primary_holder_pan_exempt VARCHAR(1),
  primary_holder_pan VARCHAR(10),
  client_type VARCHAR(1),
  account_type_1 VARCHAR(2),
  account_no_1 VARCHAR(40),
  ifsc_code_1 VARCHAR(11),
  default_bank_flag_1 VARCHAR(1),
  div_pay_mode VARCHAR(2),
  address_1 VARCHAR(40),
  address_2 VARCHAR(40),
  address_3 VARCHAR(40),
  city VARCHAR(35),
  state VARCHAR(2),
  pincode VARCHAR(10),
  country VARCHAR(35),
  email VARCHAR(50),
  communication_mode VARCHAR(1),
  indian_mobile_no VARCHAR(10),
  nominee_1_name VARCHAR(40),
  nominee_1_relation VARCHAR(40),
  nominee_1_allocation_percentage NUMERIC(5, 2),
  nominee_2_name VARCHAR(40),
  nominee_2_relation VARCHAR(40),
  nominee_2_allocation_percentage NUMERIC(5, 2),
  nominee_3_name VARCHAR(40),
  nominee_3_relation VARCHAR(40),
  nominee_3_allocation_percentage NUMERIC(5, 2),
  primary_holder_kyc_type VARCHAR(1),
  paperless_flag VARCHAR(1),
  mobile_declaration_flag VARCHAR(2),
  email_declaration_flag VARCHAR(2),
  param_payload TEXT,
  request_payload JSONB,
  response_payload JSONB,
  mf_push_status VARCHAR(30),
  mf_msg_code VARCHAR(30),
  mf_msg_desc TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
