-- Reference upsert body for MF export.
-- The executable application query, including the full source CTE and 131-position
-- MF Param payload generation, lives in:
--   server/queries/mfExportQueries.js
-- This file keeps the INSERT ... ON CONFLICT shape visible for pgAdmin review.

INSERT INTO public.mf_data (
  application_id,
  regn_type,
  client_code,
  primary_holder_first_name,
  primary_holder_middle_name,
  primary_holder_last_name,
  tax_status,
  gender,
  primary_holder_dob,
  occupation_code,
  holding_nature,
  primary_holder_pan_exempt,
  primary_holder_pan,
  client_type,
  account_type_1,
  account_no_1,
  ifsc_code_1,
  default_bank_flag_1,
  div_pay_mode,
  address_1,
  address_2,
  address_3,
  city,
  state,
  pincode,
  country,
  email,
  communication_mode,
  indian_mobile_no,
  nominee_1_name,
  nominee_1_relation,
  nominee_1_allocation_percentage,
  nominee_2_name,
  nominee_2_relation,
  nominee_2_allocation_percentage,
  nominee_3_name,
  nominee_3_relation,
  nominee_3_allocation_percentage,
  primary_holder_kyc_type,
  paperless_flag,
  mobile_declaration_flag,
  email_declaration_flag,
  param_payload,
  request_payload,
  updated_at
)
SELECT
  application_id,
  regn_type,
  client_code,
  primary_holder_first_name,
  primary_holder_middle_name,
  primary_holder_last_name,
  tax_status,
  gender,
  primary_holder_dob,
  occupation_code,
  holding_nature,
  primary_holder_pan_exempt,
  primary_holder_pan,
  client_type,
  account_type_1,
  account_no_1,
  ifsc_code_1,
  default_bank_flag_1,
  div_pay_mode,
  address_1,
  address_2,
  address_3,
  city,
  state,
  pincode,
  country,
  email,
  communication_mode,
  indian_mobile_no,
  nominee_1_name,
  nominee_1_relation,
  nominee_1_allocation_percentage,
  nominee_2_name,
  nominee_2_relation,
  nominee_2_allocation_percentage,
  nominee_3_name,
  nominee_3_relation,
  nominee_3_allocation_percentage,
  primary_holder_kyc_type,
  paperless_flag,
  mobile_declaration_flag,
  email_declaration_flag,
  param_payload,
  request_payload,
  NOW()
FROM prepared_row
WHERE application_id = $1
ON CONFLICT (application_id) DO UPDATE SET
  regn_type = EXCLUDED.regn_type,
  client_code = EXCLUDED.client_code,
  primary_holder_first_name = EXCLUDED.primary_holder_first_name,
  primary_holder_middle_name = EXCLUDED.primary_holder_middle_name,
  primary_holder_last_name = EXCLUDED.primary_holder_last_name,
  tax_status = EXCLUDED.tax_status,
  gender = EXCLUDED.gender,
  primary_holder_dob = EXCLUDED.primary_holder_dob,
  occupation_code = EXCLUDED.occupation_code,
  holding_nature = EXCLUDED.holding_nature,
  primary_holder_pan_exempt = EXCLUDED.primary_holder_pan_exempt,
  primary_holder_pan = EXCLUDED.primary_holder_pan,
  client_type = EXCLUDED.client_type,
  account_type_1 = EXCLUDED.account_type_1,
  account_no_1 = EXCLUDED.account_no_1,
  ifsc_code_1 = EXCLUDED.ifsc_code_1,
  default_bank_flag_1 = EXCLUDED.default_bank_flag_1,
  div_pay_mode = EXCLUDED.div_pay_mode,
  address_1 = EXCLUDED.address_1,
  address_2 = EXCLUDED.address_2,
  address_3 = EXCLUDED.address_3,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  pincode = EXCLUDED.pincode,
  country = EXCLUDED.country,
  email = EXCLUDED.email,
  communication_mode = EXCLUDED.communication_mode,
  indian_mobile_no = EXCLUDED.indian_mobile_no,
  nominee_1_name = EXCLUDED.nominee_1_name,
  nominee_1_relation = EXCLUDED.nominee_1_relation,
  nominee_1_allocation_percentage = EXCLUDED.nominee_1_allocation_percentage,
  nominee_2_name = EXCLUDED.nominee_2_name,
  nominee_2_relation = EXCLUDED.nominee_2_relation,
  nominee_2_allocation_percentage = EXCLUDED.nominee_2_allocation_percentage,
  nominee_3_name = EXCLUDED.nominee_3_name,
  nominee_3_relation = EXCLUDED.nominee_3_relation,
  nominee_3_allocation_percentage = EXCLUDED.nominee_3_allocation_percentage,
  primary_holder_kyc_type = EXCLUDED.primary_holder_kyc_type,
  paperless_flag = EXCLUDED.paperless_flag,
  mobile_declaration_flag = EXCLUDED.mobile_declaration_flag,
  email_declaration_flag = EXCLUDED.email_declaration_flag,
  param_payload = EXCLUDED.param_payload,
  request_payload = EXCLUDED.request_payload,
  updated_at = NOW();
