-- Reference upsert body for CVLKRA export.
-- Runtime query assembly lives in:
-- server/queries/cvlkraExportQueries.js
-- This file keeps the compact INSERT ... ON CONFLICT shape visible for pgAdmin review.

INSERT INTO public.cvlkra_data (
  application_id,
  company_code,
  batch_date,
  app_updtflg,
  app_pos_code,
  app_type,
  app_date,
  app_pan_no,
  app_pan_copy,
  app_exmt,
  app_ipv_flag,
  app_ipv_date,
  app_gen,
  app_name,
  app_f_name,
  app_dob_incorp,
  app_nationality,
  app_res_status,
  app_res_status_proof,
  app_uid_no,
  app_cor_add1,
  app_cor_add2,
  app_cor_add3,
  app_cor_city,
  app_cor_pincd,
  app_cor_state,
  app_cor_ctry,
  app_mob_no,
  app_email,
  app_cor_add_proof,
  app_cor_add_ref,
  app_cor_add_dt,
  app_per_add_flag,
  app_per_add1,
  app_per_add2,
  app_per_add3,
  app_per_city,
  app_per_pincd,
  app_per_state,
  app_per_ctry,
  app_per_add_proof,
  app_per_add_ref,
  app_per_add_dt,
  app_income,
  app_occ,
  app_pol_conn,
  app_doc_proof,
  app_mar_status,
  app_kyc_mode,
  app_ver_no,
  app_kra_code,
  app_fatca_applicable_flag,
  app_fatca_birth_place,
  app_fatca_birth_country,
  app_fatca_country_res,
  app_fatca_country_cityzenship,
  app_fatca_date_declaration,
  app_mobile_flg,
  app_email_flg,
  app_otp_refno,
  app_perm_district,
  app_corr_district,
  request_payload,
  updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
  $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
  $31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
  $41, $42, $43, $44, $45, $46, $47, $48, $49, $50,
  $51, $52, $53, $54, $55, $56, $57, $58, $59, $60,
  $61, $62, $63, NOW()
)
ON CONFLICT (application_id) DO UPDATE SET
  company_code = EXCLUDED.company_code,
  batch_date = EXCLUDED.batch_date,
  app_updtflg = EXCLUDED.app_updtflg,
  app_pos_code = EXCLUDED.app_pos_code,
  app_type = EXCLUDED.app_type,
  app_date = EXCLUDED.app_date,
  app_pan_no = EXCLUDED.app_pan_no,
  app_pan_copy = EXCLUDED.app_pan_copy,
  app_exmt = EXCLUDED.app_exmt,
  app_ipv_flag = EXCLUDED.app_ipv_flag,
  app_ipv_date = EXCLUDED.app_ipv_date,
  app_gen = EXCLUDED.app_gen,
  app_name = EXCLUDED.app_name,
  app_f_name = EXCLUDED.app_f_name,
  app_dob_incorp = EXCLUDED.app_dob_incorp,
  app_nationality = EXCLUDED.app_nationality,
  app_res_status = EXCLUDED.app_res_status,
  app_res_status_proof = EXCLUDED.app_res_status_proof,
  app_uid_no = EXCLUDED.app_uid_no,
  app_cor_add1 = EXCLUDED.app_cor_add1,
  app_cor_add2 = EXCLUDED.app_cor_add2,
  app_cor_add3 = EXCLUDED.app_cor_add3,
  app_cor_city = EXCLUDED.app_cor_city,
  app_cor_pincd = EXCLUDED.app_cor_pincd,
  app_cor_state = EXCLUDED.app_cor_state,
  app_cor_ctry = EXCLUDED.app_cor_ctry,
  app_mob_no = EXCLUDED.app_mob_no,
  app_email = EXCLUDED.app_email,
  app_cor_add_proof = EXCLUDED.app_cor_add_proof,
  app_cor_add_ref = EXCLUDED.app_cor_add_ref,
  app_cor_add_dt = EXCLUDED.app_cor_add_dt,
  app_per_add_flag = EXCLUDED.app_per_add_flag,
  app_per_add1 = EXCLUDED.app_per_add1,
  app_per_add2 = EXCLUDED.app_per_add2,
  app_per_add3 = EXCLUDED.app_per_add3,
  app_per_city = EXCLUDED.app_per_city,
  app_per_pincd = EXCLUDED.app_per_pincd,
  app_per_state = EXCLUDED.app_per_state,
  app_per_ctry = EXCLUDED.app_per_ctry,
  app_per_add_proof = EXCLUDED.app_per_add_proof,
  app_per_add_ref = EXCLUDED.app_per_add_ref,
  app_per_add_dt = EXCLUDED.app_per_add_dt,
  app_income = EXCLUDED.app_income,
  app_occ = EXCLUDED.app_occ,
  app_pol_conn = EXCLUDED.app_pol_conn,
  app_doc_proof = EXCLUDED.app_doc_proof,
  app_mar_status = EXCLUDED.app_mar_status,
  app_kyc_mode = EXCLUDED.app_kyc_mode,
  app_ver_no = EXCLUDED.app_ver_no,
  app_kra_code = EXCLUDED.app_kra_code,
  app_fatca_applicable_flag = EXCLUDED.app_fatca_applicable_flag,
  app_fatca_birth_place = EXCLUDED.app_fatca_birth_place,
  app_fatca_birth_country = EXCLUDED.app_fatca_birth_country,
  app_fatca_country_res = EXCLUDED.app_fatca_country_res,
  app_fatca_country_cityzenship = EXCLUDED.app_fatca_country_cityzenship,
  app_fatca_date_declaration = EXCLUDED.app_fatca_date_declaration,
  app_mobile_flg = EXCLUDED.app_mobile_flg,
  app_email_flg = EXCLUDED.app_email_flg,
  app_otp_refno = EXCLUDED.app_otp_refno,
  app_perm_district = EXCLUDED.app_perm_district,
  app_corr_district = EXCLUDED.app_corr_district,
  request_payload = EXCLUDED.request_payload,
  updated_at = NOW();
