const pool = require("../config/db");


const insertTechexcelData = async (userRecord) => {
  const query = `
    INSERT INTO public.techexcel (
      "ANNUAL_INCOME",
      "AcOpeLocation",
      "Address_Proof1",
      "Agreement_Date",
      "BFile_Other1",
      "BFile_Other2",
      "BFile_Other3",
      "BFile_Other4",
      "BFile_Pan",
      "BFile_Photo",
      "BIRTH_DATE",
      "BO_CATEGORY_CODE",
      "BO_SUB_STATUS_CODE",
      "BRANCH_CODE",
      "BoStatusCode",
      "Bo_Acc_Open_src",
      "CATEGORY",
      "CKYCFLAG",
      "CLFundTrf",
      "CL_OP_CHGS_DEBITED",
      "CONSIDER_SOH_MARGIN",
      "CUSI_CLIENT",
      "Category",
      "City",
      "Client_Name",
      "Client_Nature",
      "Client_WebXID",
      "Client_id",
      "Con_not",
      "Correspondance_Address_Proof",
      "Country",
      "Csc_flg",
      "DELIVERY_TYPE",
      "DR_INTEREST",
      "EMAIL_ID",
      "ExchangeList",
      "FIRST_NAME",
      "FIXEDMAKERCHECKER",
      "Fatca_Country",
      "Fatca_Declaration",
      "Father_Husband_Name",
      "Father_Husband_Name1",
      "Father_Husband_Name2",
      "Father_Husband_Name3",
      "GRP1ACTIVE",
      "GRP2ACTIVE",
      "GUARDIAN_ADDR",
      "GUARDIAN_DOB2",
      "GUARDIAN_DOB3",
      "GUARDIAN_NAME",
      "GUARDIAN_PAN",
      "GUARDIAN_PAN2",
      "GUARDIAN_PAN3",
      "GUARDIAN_TITLE2",
      "GUARDIAN_TITLE3",
      "GUARDIAN_mobile_no",
      "GUARDIAN_relation",
      "GrossAnnualIncomeDate",
      "Guar1_address2",
      "Guar1_address3",
      "Guar1_city",
      "Guar1_country",
      "Guar1_email",
      "Guar1_pin_code",
      "Guar1_proof_details",
      "Guar1_proof_id",
      "Guar2_address",
      "Guar2_address2",
      "Guar2_address3",
      "Guar2_city",
      "Guar2_country",
      "Guar2_email",
      "Guar2_mobile_no",
      "Guar2_pin_code",
      "Guar2_proof_id",
      "Guar2_relation",
      "Guar2_state",
      "Guar3_address",
      "Guar3_address2",
      "Guar3_address3",
      "Guar3_city",
      "Guar3_country",
      "Guar3_email",
      "Guar3_mobile_no",
      "Guar3_pin_code",
      "Guar3_proof_id",
      "Guar3_relation",
      "Guar3_state",
      "Guardian_Name2",
      "Guardian_Name3",
      "IBT_CHGSDROption",
      "IBT_FLAG",
      "IBT_MODULE",
      "INPERSON_DATE",
      "INSTBOID",
      "INTER_SETTLEMENT_CHARGE",
      "INTRODUCER_ACC_CODE",
      "INTRODUCER_ADDRESS",
      "INTRODUCER_NAME",
      "INTR_FIRST_NAME",
      "INTR_LAST_NAME",
      "INTR_MIDDLE_NAME",
      "IPV_EMP_ORG",
      "InterestDebiting",
      "Ipv_emp_code",
      "Ipv_emp_org",
      "Ipv_emp_place",
      "IsInternetTrading",
      "KYC_MODE_TYPE",
      "KraRec",
      "KraRecUP",
      "LAST_NAME",
      "MARITAL_STATUS",
      "MIDDLE_NAME",
      "MIN_OP_CHARGES",
      "MOBILE_NO",
      "MTFCl",
      "MTFClAuto",
      "MTF_Close",
      "Master_Pan_Purpose",
      "Mode_of_operation",
      "ModuleCode",
      "Mother_Name",
      "NACHFLAG",
      "NATIONALITY",
      "NOMINATION_TITLE",
      "NOMINATION_TITLE2",
      "NOMINATION_TITLE3",
      "NOMINEEOPTOUT",
      "NOMINEE_PIN_CODE",
      "NOM_EMAIL",
      "NOT_BANK_NAME",
      "NOT_BOID",
      "NOT_DDPI",
      "NOT_DIET_CHARGES",
      "NOT_DPID",
      "NOT_EFT",
      "NOT_IFSC",
      "NOT_M1_BSE_CASH",
      "NOT_M1_NSE_CASH",
      "NOT_M2_BSE_CASH",
      "NOT_M2_NSE_CASH",
      "NOT_PIS",
      "NOT_POA",
      "NOT_PROOF_REC",
      "NRIPIS",
      "No_Of_Holder",
      "No_Of_Nominee",
      "Nom2_address",
      "Nom2_address2",
      "Nom2_address3",
      "Nom3_address",
      "Nom3_address2",
      "Nom3_address3",
      "Nom_City",
      "Nom_City2",
      "Nom_City3",
      "Nom_DOB",
      "Nom_DOB2",
      "Nom_DOB3",
      "Nom_Email2",
      "Nom_Email3",
      "Nom_Phone",
      "Nom_Phone2",
      "Nom_Phone3",
      "Nom_Relation",
      "Nom_Relation2",
      "Nom_Relation3",
      "Nom_State",
      "Nom_State2",
      "Nom_State3",
      "Nom_address",
      "Nom_address2",
      "Nom_address3",
      "Nom_country2",
      "Nom_country3",
      "Nom_pan",
      "Nom_pan2",
      "Nom_pan3",
      "Nomination_Name",
      "Nomination_Name2",
      "Nomination_Name3",
      "Nominee_Pin_Code2",
      "Nominee_Pin_Code3",
      "Not_BANKCCOUNTNNO",
      "Not_BankAcType",
      "Not_MicrNo",
      "Not_PROOF_REC",
      "OCCUPATION",
      "Occupation_Others",
      "Off_State",
      "PAN_NO",
      "PERSON_VERIFY_DESIGNATION",
      "POA_SECURITY_PAYINDATE",
      "POOL_HOLD_CHARGE",
      "Pan_Flag1",
      "Pan_Name",
      "Pan_Proof",
      "Payment_Request",
      "Person_Verify_Designation",
      "Person_verify",
      "Person_verify_Name",
      "Pin_Code",
      "Political_Affilication",
      "PrintBill",
      "QUALIFICATION",
      "REG_ADDR1",
      "REG_ADDR2",
      "REG_ADDR3",
      "RESI_ADDRESS1",
      "RESI_ADDRESS2",
      "RESI_ADDRESS3",
      "RESI_TEL_NO",
      "RETANTION_AUTHO_LETTER",
      "R_CITY",
      "R_COUNTRY",
      "R_PIN_CODE",
      "R_STATE",
      "RelationManager_CODE",
      "Residential_Status",
      "Risk_catg",
      "SERIAL_NO",
      "SEX",
      "SMS_SEND",
      "STATMENT_OPTION",
      "STD_CODE",
      "SameAddress",
      "SameRegAddFor_Nom2",
      "Settlement_Type",
      "Share_Percentage",
      "Share_Percentage2",
      "Share_Percentage3",
      "State",
      "Stetement_Communication_Mode",
      "TITLE",
      "TRUSTBASEPAYIN",
      "TypeOfFacility",
      "UpdationFlag",
      "WebAC"
    ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, $91, $92, $93, $94, $95, $96, $97, $98, $99, $100, $101, $102, $103, $104, $105, $106, $107, $108, $109, $110, $111, $112, $113, $114, $115, $116, $117, $118, $119, $120, $121, $122, $123, $124, $125, $126, $127, $128, $129, $130, $131, $132, $133, $134, $135, $136, $137, $138, $139, $140, $141, $142, $143, $144, $145, $146, $147, $148, $149, $150, $151, $152, $153, $154, $155, $156, $157, $158, $159, $160, $161, $162, $163, $164, $165, $166, $167, $168, $169, $170, $171, $172, $173, $174, $175, $176, $177, $178, $179, $180, $181, $182, $183, $184, $185, $186, $187, $188, $189, $190, $191, $192, $193, $194, $195, $196, $197, $198, $199, $200, $201, $202, $203, $204, $205, $206, $207, $208, $209, $210, $211, $212, $213, $214, $215, $216, $217, $218, $219, $220, $221, $222, $223, $224, $225, $226, $227, $228, $229, $230, $231, $232, $233, $234, $235, $236, $237, $238, $239
    )
    ON CONFLICT ("Client_id") DO UPDATE SET
      "ANNUAL_INCOME" = EXCLUDED."ANNUAL_INCOME",
      "AcOpeLocation" = EXCLUDED."AcOpeLocation",
      "Address_Proof1" = EXCLUDED."Address_Proof1",
      "Agreement_Date" = EXCLUDED."Agreement_Date",
      "BFile_Other1" = EXCLUDED."BFile_Other1",
      "BFile_Other2" = EXCLUDED."BFile_Other2",
      "BFile_Other3" = EXCLUDED."BFile_Other3",
      "BFile_Other4" = EXCLUDED."BFile_Other4",
      "BFile_Pan" = EXCLUDED."BFile_Pan",
      "BFile_Photo" = EXCLUDED."BFile_Photo",
      "BIRTH_DATE" = EXCLUDED."BIRTH_DATE",
      "BO_CATEGORY_CODE" = EXCLUDED."BO_CATEGORY_CODE",
      "BO_SUB_STATUS_CODE" = EXCLUDED."BO_SUB_STATUS_CODE",
      "BRANCH_CODE" = EXCLUDED."BRANCH_CODE",
      "BoStatusCode" = EXCLUDED."BoStatusCode",
      "Bo_Acc_Open_src" = EXCLUDED."Bo_Acc_Open_src",
      "CATEGORY" = EXCLUDED."CATEGORY",
      "CKYCFLAG" = EXCLUDED."CKYCFLAG",
      "CLFundTrf" = EXCLUDED."CLFundTrf",
      "CL_OP_CHGS_DEBITED" = EXCLUDED."CL_OP_CHGS_DEBITED",
      "CONSIDER_SOH_MARGIN" = EXCLUDED."CONSIDER_SOH_MARGIN",
      "CUSI_CLIENT" = EXCLUDED."CUSI_CLIENT",
      "Category" = EXCLUDED."Category",
      "City" = EXCLUDED."City",
      "Client_Name" = EXCLUDED."Client_Name",
      "Client_Nature" = EXCLUDED."Client_Nature",
      "Client_WebXID" = EXCLUDED."Client_WebXID",
      "Client_id" = EXCLUDED."Client_id",
      "Con_not" = EXCLUDED."Con_not",
      "Correspondance_Address_Proof" = EXCLUDED."Correspondance_Address_Proof",
      "Country" = EXCLUDED."Country",
      "Csc_flg" = EXCLUDED."Csc_flg",
      "DELIVERY_TYPE" = EXCLUDED."DELIVERY_TYPE",
      "DR_INTEREST" = EXCLUDED."DR_INTEREST",
      "EMAIL_ID" = EXCLUDED."EMAIL_ID",
      "ExchangeList" = EXCLUDED."ExchangeList",
      "FIRST_NAME" = EXCLUDED."FIRST_NAME",
      "FIXEDMAKERCHECKER" = EXCLUDED."FIXEDMAKERCHECKER",
      "Fatca_Country" = EXCLUDED."Fatca_Country",
      "Fatca_Declaration" = EXCLUDED."Fatca_Declaration",
      "Father_Husband_Name" = EXCLUDED."Father_Husband_Name",
      "Father_Husband_Name1" = EXCLUDED."Father_Husband_Name1",
      "Father_Husband_Name2" = EXCLUDED."Father_Husband_Name2",
      "Father_Husband_Name3" = EXCLUDED."Father_Husband_Name3",
      "GRP1ACTIVE" = EXCLUDED."GRP1ACTIVE",
      "GRP2ACTIVE" = EXCLUDED."GRP2ACTIVE",
      "GUARDIAN_ADDR" = EXCLUDED."GUARDIAN_ADDR",
      "GUARDIAN_DOB2" = EXCLUDED."GUARDIAN_DOB2",
      "GUARDIAN_DOB3" = EXCLUDED."GUARDIAN_DOB3",
      "GUARDIAN_NAME" = EXCLUDED."GUARDIAN_NAME",
      "GUARDIAN_PAN" = EXCLUDED."GUARDIAN_PAN",
      "GUARDIAN_PAN2" = EXCLUDED."GUARDIAN_PAN2",
      "GUARDIAN_PAN3" = EXCLUDED."GUARDIAN_PAN3",
      "GUARDIAN_TITLE2" = EXCLUDED."GUARDIAN_TITLE2",
      "GUARDIAN_TITLE3" = EXCLUDED."GUARDIAN_TITLE3",
      "GUARDIAN_mobile_no" = EXCLUDED."GUARDIAN_mobile_no",
      "GUARDIAN_relation" = EXCLUDED."GUARDIAN_relation",
      "GrossAnnualIncomeDate" = EXCLUDED."GrossAnnualIncomeDate",
      "Guar1_address2" = EXCLUDED."Guar1_address2",
      "Guar1_address3" = EXCLUDED."Guar1_address3",
      "Guar1_city" = EXCLUDED."Guar1_city",
      "Guar1_country" = EXCLUDED."Guar1_country",
      "Guar1_email" = EXCLUDED."Guar1_email",
      "Guar1_pin_code" = EXCLUDED."Guar1_pin_code",
      "Guar1_proof_details" = EXCLUDED."Guar1_proof_details",
      "Guar1_proof_id" = EXCLUDED."Guar1_proof_id",
      "Guar2_address" = EXCLUDED."Guar2_address",
      "Guar2_address2" = EXCLUDED."Guar2_address2",
      "Guar2_address3" = EXCLUDED."Guar2_address3",
      "Guar2_city" = EXCLUDED."Guar2_city",
      "Guar2_country" = EXCLUDED."Guar2_country",
      "Guar2_email" = EXCLUDED."Guar2_email",
      "Guar2_mobile_no" = EXCLUDED."Guar2_mobile_no",
      "Guar2_pin_code" = EXCLUDED."Guar2_pin_code",
      "Guar2_proof_id" = EXCLUDED."Guar2_proof_id",
      "Guar2_relation" = EXCLUDED."Guar2_relation",
      "Guar2_state" = EXCLUDED."Guar2_state",
      "Guar3_address" = EXCLUDED."Guar3_address",
      "Guar3_address2" = EXCLUDED."Guar3_address2",
      "Guar3_address3" = EXCLUDED."Guar3_address3",
      "Guar3_city" = EXCLUDED."Guar3_city",
      "Guar3_country" = EXCLUDED."Guar3_country",
      "Guar3_email" = EXCLUDED."Guar3_email",
      "Guar3_mobile_no" = EXCLUDED."Guar3_mobile_no",
      "Guar3_pin_code" = EXCLUDED."Guar3_pin_code",
      "Guar3_proof_id" = EXCLUDED."Guar3_proof_id",
      "Guar3_relation" = EXCLUDED."Guar3_relation",
      "Guar3_state" = EXCLUDED."Guar3_state",
      "Guardian_Name2" = EXCLUDED."Guardian_Name2",
      "Guardian_Name3" = EXCLUDED."Guardian_Name3",
      "IBT_CHGSDROption" = EXCLUDED."IBT_CHGSDROption",
      "IBT_FLAG" = EXCLUDED."IBT_FLAG",
      "IBT_MODULE" = EXCLUDED."IBT_MODULE",
      "INPERSON_DATE" = EXCLUDED."INPERSON_DATE",
      "INSTBOID" = EXCLUDED."INSTBOID",
      "INTER_SETTLEMENT_CHARGE" = EXCLUDED."INTER_SETTLEMENT_CHARGE",
      "INTRODUCER_ACC_CODE" = EXCLUDED."INTRODUCER_ACC_CODE",
      "INTRODUCER_ADDRESS" = EXCLUDED."INTRODUCER_ADDRESS",
      "INTRODUCER_NAME" = EXCLUDED."INTRODUCER_NAME",
      "INTR_FIRST_NAME" = EXCLUDED."INTR_FIRST_NAME",
      "INTR_LAST_NAME" = EXCLUDED."INTR_LAST_NAME",
      "INTR_MIDDLE_NAME" = EXCLUDED."INTR_MIDDLE_NAME",
      "IPV_EMP_ORG" = EXCLUDED."IPV_EMP_ORG",
      "InterestDebiting" = EXCLUDED."InterestDebiting",
      "Ipv_emp_code" = EXCLUDED."Ipv_emp_code",
      "Ipv_emp_org" = EXCLUDED."Ipv_emp_org",
      "Ipv_emp_place" = EXCLUDED."Ipv_emp_place",
      "IsInternetTrading" = EXCLUDED."IsInternetTrading",
      "KYC_MODE_TYPE" = EXCLUDED."KYC_MODE_TYPE",
      "KraRec" = EXCLUDED."KraRec",
      "KraRecUP" = EXCLUDED."KraRecUP",
      "LAST_NAME" = EXCLUDED."LAST_NAME",
      "MARITAL_STATUS" = EXCLUDED."MARITAL_STATUS",
      "MIDDLE_NAME" = EXCLUDED."MIDDLE_NAME",
      "MIN_OP_CHARGES" = EXCLUDED."MIN_OP_CHARGES",
      "MOBILE_NO" = EXCLUDED."MOBILE_NO",
      "MTFCl" = EXCLUDED."MTFCl",
      "MTFClAuto" = EXCLUDED."MTFClAuto",
      "MTF_Close" = EXCLUDED."MTF_Close",
      "Master_Pan_Purpose" = EXCLUDED."Master_Pan_Purpose",
      "Mode_of_operation" = EXCLUDED."Mode_of_operation",
      "ModuleCode" = EXCLUDED."ModuleCode",
      "Mother_Name" = EXCLUDED."Mother_Name",
      "NACHFLAG" = EXCLUDED."NACHFLAG",
      "NATIONALITY" = EXCLUDED."NATIONALITY",
      "NOMINATION_TITLE" = EXCLUDED."NOMINATION_TITLE",
      "NOMINATION_TITLE2" = EXCLUDED."NOMINATION_TITLE2",
      "NOMINATION_TITLE3" = EXCLUDED."NOMINATION_TITLE3",
      "NOMINEEOPTOUT" = EXCLUDED."NOMINEEOPTOUT",
      "NOMINEE_PIN_CODE" = EXCLUDED."NOMINEE_PIN_CODE",
      "NOM_EMAIL" = EXCLUDED."NOM_EMAIL",
      "NOT_BANK_NAME" = EXCLUDED."NOT_BANK_NAME",
      "NOT_BOID" = EXCLUDED."NOT_BOID",
      "NOT_DDPI" = EXCLUDED."NOT_DDPI",
      "NOT_DIET_CHARGES" = EXCLUDED."NOT_DIET_CHARGES",
      "NOT_DPID" = EXCLUDED."NOT_DPID",
      "NOT_EFT" = EXCLUDED."NOT_EFT",
      "NOT_IFSC" = EXCLUDED."NOT_IFSC",
      "NOT_M1_BSE_CASH" = EXCLUDED."NOT_M1_BSE_CASH",
      "NOT_M1_NSE_CASH" = EXCLUDED."NOT_M1_NSE_CASH",
      "NOT_M2_BSE_CASH" = EXCLUDED."NOT_M2_BSE_CASH",
      "NOT_M2_NSE_CASH" = EXCLUDED."NOT_M2_NSE_CASH",
      "NOT_PIS" = EXCLUDED."NOT_PIS",
      "NOT_POA" = EXCLUDED."NOT_POA",
      "NOT_PROOF_REC" = EXCLUDED."NOT_PROOF_REC",
      "NRIPIS" = EXCLUDED."NRIPIS",
      "No_Of_Holder" = EXCLUDED."No_Of_Holder",
      "No_Of_Nominee" = EXCLUDED."No_Of_Nominee",
      "Nom2_address" = EXCLUDED."Nom2_address",
      "Nom2_address2" = EXCLUDED."Nom2_address2",
      "Nom2_address3" = EXCLUDED."Nom2_address3",
      "Nom3_address" = EXCLUDED."Nom3_address",
      "Nom3_address2" = EXCLUDED."Nom3_address2",
      "Nom3_address3" = EXCLUDED."Nom3_address3",
      "Nom_City" = EXCLUDED."Nom_City",
      "Nom_City2" = EXCLUDED."Nom_City2",
      "Nom_City3" = EXCLUDED."Nom_City3",
      "Nom_DOB" = EXCLUDED."Nom_DOB",
      "Nom_DOB2" = EXCLUDED."Nom_DOB2",
      "Nom_DOB3" = EXCLUDED."Nom_DOB3",
      "Nom_Email2" = EXCLUDED."Nom_Email2",
      "Nom_Email3" = EXCLUDED."Nom_Email3",
      "Nom_Phone" = EXCLUDED."Nom_Phone",
      "Nom_Phone2" = EXCLUDED."Nom_Phone2",
      "Nom_Phone3" = EXCLUDED."Nom_Phone3",
      "Nom_Relation" = EXCLUDED."Nom_Relation",
      "Nom_Relation2" = EXCLUDED."Nom_Relation2",
      "Nom_Relation3" = EXCLUDED."Nom_Relation3",
      "Nom_State" = EXCLUDED."Nom_State",
      "Nom_State2" = EXCLUDED."Nom_State2",
      "Nom_State3" = EXCLUDED."Nom_State3",
      "Nom_address" = EXCLUDED."Nom_address",
      "Nom_address2" = EXCLUDED."Nom_address2",
      "Nom_address3" = EXCLUDED."Nom_address3",
      "Nom_country2" = EXCLUDED."Nom_country2",
      "Nom_country3" = EXCLUDED."Nom_country3",
      "Nom_pan" = EXCLUDED."Nom_pan",
      "Nom_pan2" = EXCLUDED."Nom_pan2",
      "Nom_pan3" = EXCLUDED."Nom_pan3",
      "Nomination_Name" = EXCLUDED."Nomination_Name",
      "Nomination_Name2" = EXCLUDED."Nomination_Name2",
      "Nomination_Name3" = EXCLUDED."Nomination_Name3",
      "Nominee_Pin_Code2" = EXCLUDED."Nominee_Pin_Code2",
      "Nominee_Pin_Code3" = EXCLUDED."Nominee_Pin_Code3",
      "Not_BANKCCOUNTNNO" = EXCLUDED."Not_BANKCCOUNTNNO",
      "Not_BankAcType" = EXCLUDED."Not_BankAcType",
      "Not_MicrNo" = EXCLUDED."Not_MicrNo",
      "Not_PROOF_REC" = EXCLUDED."Not_PROOF_REC",
      "OCCUPATION" = EXCLUDED."OCCUPATION",
      "Occupation_Others" = EXCLUDED."Occupation_Others",
      "Off_State" = EXCLUDED."Off_State",
      "PAN_NO" = EXCLUDED."PAN_NO",
      "PERSON_VERIFY_DESIGNATION" = EXCLUDED."PERSON_VERIFY_DESIGNATION",
      "POA_SECURITY_PAYINDATE" = EXCLUDED."POA_SECURITY_PAYINDATE",
      "POOL_HOLD_CHARGE" = EXCLUDED."POOL_HOLD_CHARGE",
      "Pan_Flag1" = EXCLUDED."Pan_Flag1",
      "Pan_Name" = EXCLUDED."Pan_Name",
      "Pan_Proof" = EXCLUDED."Pan_Proof",
      "Payment_Request" = EXCLUDED."Payment_Request",
      "Person_Verify_Designation" = EXCLUDED."Person_Verify_Designation",
      "Person_verify" = EXCLUDED."Person_verify",
      "Person_verify_Name" = EXCLUDED."Person_verify_Name",
      "Pin_Code" = EXCLUDED."Pin_Code",
      "Political_Affilication" = EXCLUDED."Political_Affilication",
      "PrintBill" = EXCLUDED."PrintBill",
      "QUALIFICATION" = EXCLUDED."QUALIFICATION",
      "REG_ADDR1" = EXCLUDED."REG_ADDR1",
      "REG_ADDR2" = EXCLUDED."REG_ADDR2",
      "REG_ADDR3" = EXCLUDED."REG_ADDR3",
      "RESI_ADDRESS1" = EXCLUDED."RESI_ADDRESS1",
      "RESI_ADDRESS2" = EXCLUDED."RESI_ADDRESS2",
      "RESI_ADDRESS3" = EXCLUDED."RESI_ADDRESS3",
      "RESI_TEL_NO" = EXCLUDED."RESI_TEL_NO",
      "RETANTION_AUTHO_LETTER" = EXCLUDED."RETANTION_AUTHO_LETTER",
      "R_CITY" = EXCLUDED."R_CITY",
      "R_COUNTRY" = EXCLUDED."R_COUNTRY",
      "R_PIN_CODE" = EXCLUDED."R_PIN_CODE",
      "R_STATE" = EXCLUDED."R_STATE",
      "RelationManager_CODE" = EXCLUDED."RelationManager_CODE",
      "Residential_Status" = EXCLUDED."Residential_Status",
      "Risk_catg" = EXCLUDED."Risk_catg",
      "SERIAL_NO" = EXCLUDED."SERIAL_NO",
      "SEX" = EXCLUDED."SEX",
      "SMS_SEND" = EXCLUDED."SMS_SEND",
      "STATMENT_OPTION" = EXCLUDED."STATMENT_OPTION",
      "STD_CODE" = EXCLUDED."STD_CODE",
      "SameAddress" = EXCLUDED."SameAddress",
      "SameRegAddFor_Nom2" = EXCLUDED."SameRegAddFor_Nom2",
      "Settlement_Type" = EXCLUDED."Settlement_Type",
      "Share_Percentage" = EXCLUDED."Share_Percentage",
      "Share_Percentage2" = EXCLUDED."Share_Percentage2",
      "Share_Percentage3" = EXCLUDED."Share_Percentage3",
      "State" = EXCLUDED."State",
      "Stetement_Communication_Mode" = EXCLUDED."Stetement_Communication_Mode",
      "TITLE" = EXCLUDED."TITLE",
      "TRUSTBASEPAYIN" = EXCLUDED."TRUSTBASEPAYIN",
      "TypeOfFacility" = EXCLUDED."TypeOfFacility",
      "UpdationFlag" = EXCLUDED."UpdationFlag",
      "WebAC" = EXCLUDED."WebAC"
    RETURNING *;
  `;

  const values = [
    userRecord.annual_income || "",
    userRecord.ac_ope_location || "",
    userRecord.address_proof1 || "",
    userRecord.agreement_date || "",
    userRecord.bfile_other1 || "",
    userRecord.bfile_other2 || "",
    userRecord.bfile_other3 || "",
    userRecord.bfile_other4 || "",
    userRecord.bfile_pan || "",
    userRecord.bfile_photo || "",
    userRecord.birth_date || "",
    userRecord.bo_category_code || "",
    userRecord.bo_sub_status_code || "",
    userRecord.branch_code || "",
    userRecord.bo_status_code || "",
    userRecord.bo_acc_open_src || "",
    userRecord.category || "",
    userRecord.ckycflag || "",
    userRecord.cl_fund_trf || "",
    userRecord.cl_op_chgs_debited || "",
    userRecord.consider_soh_margin || "",
    userRecord.cusi_client || "",
    userRecord.category_dup || "",
    userRecord.city || "",
    userRecord.client_name || "",
    userRecord.client_nature || "",
    userRecord.client_web_xid || "",
    userRecord.client_id || "",
    userRecord.con_not || "",
    userRecord.correspondance_address_proof || "",
    userRecord.country || "",
    userRecord.csc_flg || "",
    userRecord.delivery_type || "",
    userRecord.dr_interest || "",
    userRecord.email_id || "",
    userRecord.exchange_list || "",
    userRecord.first_name || "",
    userRecord.fixed_maker_checker || "",
    userRecord.fatca_country || "",
    userRecord.fatca_declaration || "",
    userRecord.father_husband_name || "",
    userRecord.father_husband_name1 || "",
    userRecord.father_husband_name2 || "",
    userRecord.father_husband_name3 || "",
    userRecord.grp1_active || "",
    userRecord.grp2_active || "",
    userRecord.guardian_addr || "",
    userRecord.guardian_dob2 || "",
    userRecord.guardian_dob3 || "",
    userRecord.guardian_name || "",
    userRecord.guardian_pan || "",
    userRecord.guardian_pan2 || "",
    userRecord.guardian_pan3 || "",
    userRecord.guardian_title2 || "",
    userRecord.guardian_title3 || "",
    userRecord.guardian_mobile_no || "",
    userRecord.guardian_relation || "",
    userRecord.gross_annual_income_date || "",
    userRecord.guar1_address2 || "",
    userRecord.guar1_address3 || "",
    userRecord.guar1_city || "",
    userRecord.guar1_country || "",
    userRecord.guar1_email || "",
    userRecord.guar1_pin_code || "",
    userRecord.guar1_proof_details || "",
    userRecord.guar1_proof_id || "",
    userRecord.guar2_address || "",
    userRecord.guar2_address2 || "",
    userRecord.guar2_address3 || "",
    userRecord.guar2_city || "",
    userRecord.guar2_country || "",
    userRecord.guar2_email || "",
    userRecord.guar2_mobile_no || "",
    userRecord.guar2_pin_code || "",
    userRecord.guar2_proof_id || "",
    userRecord.guar2_relation || "",
    userRecord.guar2_state || "",
    userRecord.guar3_address || "",
    userRecord.guar3_address2 || "",
    userRecord.guar3_address3 || "",
    userRecord.guar3_city || "",
    userRecord.guar3_country || "",
    userRecord.guar3_email || "",
    userRecord.guar3_mobile_no || "",
    userRecord.guar3_pin_code || "",
    userRecord.guar3_proof_id || "",
    userRecord.guar3_relation || "",
    userRecord.guar3_state || "",
    userRecord.guardian_name2 || "",
    userRecord.guardian_name3 || "",
    userRecord.ibt_chgs_dr_option || "",
    userRecord.ibt_flag || "",
    userRecord.ibt_module || "",
    userRecord.inperson_date || "",
    userRecord.inst_boid || "",
    userRecord.inter_settlement_charge || "",
    userRecord.introducer_acc_code || "",
    userRecord.introducer_address || "",
    userRecord.introducer_name || "",
    userRecord.intr_first_name || "",
    userRecord.intr_last_name || "",
    userRecord.intr_middle_name || "",
    userRecord.ipv_emp_org || "",
    userRecord.interest_debiting || "",
    userRecord.ipv_emp_code || "",
    userRecord.ipv_emp_org_dup || "",
    userRecord.ipv_emp_place || "",
    userRecord.is_internet_trading || "",
    userRecord.kyc_mode_type || "",
    userRecord.kra_rec || "",
    userRecord.kra_rec_up || "",
    userRecord.last_name || "",
    userRecord.marital_status || "",
    userRecord.middle_name || "",
    userRecord.min_op_charges || "",
    userRecord.mobile_no || "",
    userRecord.mtf_cl || "",
    userRecord.mtf_cl_auto || "",
    userRecord.mtf_close || "",
    userRecord.master_pan_purpose || "",
    userRecord.mode_of_operation || "",
    userRecord.module_code || "",
    userRecord.mother_name || "",
    userRecord.nach_flag || "",
    userRecord.nationality || "",
    userRecord.nomination_title || "",
    userRecord.nomination_title2 || "",
    userRecord.nomination_title3 || "",
    userRecord.nominee_opt_out || "",
    userRecord.nominee_pin_code || "",
    userRecord.nom_email || "",
    userRecord.not_bank_name || "",
    userRecord.not_boid || "",
    userRecord.not_ddpi || "",
    userRecord.not_diet_charges || "",
    userRecord.not_dpid || "",
    userRecord.not_eft || "",
    userRecord.not_ifsc || "",
    userRecord.not_m1_bse_cash || "",
    userRecord.not_m1_nse_cash || "",
    userRecord.not_m2_bse_cash || "",
    userRecord.not_m2_nse_cash || "",
    userRecord.not_pis || "",
    userRecord.not_poa || "",
    userRecord.not_proof_rec || "",
    userRecord.nripis || "",
    userRecord.no_of_holder || "",
    userRecord.no_of_nominee || "",
    userRecord.nom2_address || "",
    userRecord.nom2_address2 || "",
    userRecord.nom2_address3 || "",
    userRecord.nom3_address || "",
    userRecord.nom3_address2 || "",
    userRecord.nom3_address3 || "",
    userRecord.nom_city || "",
    userRecord.nom_city2 || "",
    userRecord.nom_city3 || "",
    userRecord.nom_dob || "",
    userRecord.nom_dob2 || "",
    userRecord.nom_dob3 || "",
    userRecord.nom_email2 || "",
    userRecord.nom_email3 || "",
    userRecord.nom_phone || "",
    userRecord.nom_phone2 || "",
    userRecord.nom_phone3 || "",
    userRecord.nom_relation || "",
    userRecord.nom_relation2 || "",
    userRecord.nom_relation3 || "",
    userRecord.nom_state || "",
    userRecord.nom_state2 || "",
    userRecord.nom_state3 || "",
    userRecord.nom_address || "",
    userRecord.nom_address2 || "",
    userRecord.nom_address3 || "",
    userRecord.nom_country2 || "",
    userRecord.nom_country3 || "",
    userRecord.nom_pan || "",
    userRecord.nom_pan2 || "",
    userRecord.nom_pan3 || "",
    userRecord.nomination_name || "",
    userRecord.nomination_name2 || "",
    userRecord.nomination_name3 || "",
    userRecord.nominee_pin_code2 || "",
    userRecord.nominee_pin_code3 || "",
    userRecord.not_bank_account_no || "",
    userRecord.not_bank_ac_type || "",
    userRecord.not_micr_no || "",
    userRecord.not_proof_rec_dup || "",
    userRecord.occupation || "",
    userRecord.occupation_others || "",
    userRecord.off_state || "",
    userRecord.pan_no || "",
    userRecord.person_verify_designation || "",
    userRecord.poa_security_payin_date || "",
    userRecord.pool_hold_charge || "",
    userRecord.pan_flag1 || "",
    userRecord.pan_name || "",
    userRecord.pan_proof || "",
    userRecord.payment_request || "",
    userRecord.person_verify_designation_dup || "",
    userRecord.person_verify || "",
    userRecord.person_verify_name || "",
    userRecord.pin_code || "",
    userRecord.political_affiliation || "",
    userRecord.print_bill || "",
    userRecord.qualification || "",
    userRecord.reg_addr1 || "",
    userRecord.reg_addr2 || "",
    userRecord.reg_addr3 || "",
    userRecord.resi_address1 || "",
    userRecord.resi_address2 || "",
    userRecord.resi_address3 || "",
    userRecord.resi_tel_no || "",
    userRecord.retention_autho_letter || "",
    userRecord.r_city || "",
    userRecord.r_country || "",
    userRecord.r_pin_code || "",
    userRecord.r_state || "",
    userRecord.relation_manager_code || "",
    userRecord.residential_status || "",
    userRecord.risk_catg || "",
    userRecord.serial_no || "",
    userRecord.sex || "",
    userRecord.sms_send || "",
    userRecord.statement_option || "",
    userRecord.std_code || "",
    userRecord.same_address || "",
    userRecord.same_reg_add_for_nom2 || "",
    userRecord.settlement_type || "",
    userRecord.share_percentage || "",
    userRecord.share_percentage2 || "",
    userRecord.share_percentage3 || "",
    userRecord.state || "",
    userRecord.statement_communication_mode || "",
    userRecord.title || "",
    userRecord.trust_base_payin || "",
    userRecord.type_of_facility || "",
    userRecord.updation_flag || "",
    userRecord.web_ac || ""
  ];

  return await pool.query(query, values);
};

module.exports = {
  insertTechexcelData
};
